# FROM rust as build
FROM neomantra/aeron-cpp-debian:1.28.2 AS aeron-builder

ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH \
    RUST_VERSION=1.61.0
RUN USER=root apt-get update && \
    apt-get -y upgrade && \
    apt-get -y install git curl g++ build-essential libssl-dev pkg-config && \
    apt-get -y install software-properties-common && \
    # apt-get -y install iputils-ping && \
    apt-get update 
# create a new empty shell project
RUN USER=root curl https://sh.rustup.rs -sSf | sh -s -- -y 
RUN chmod 600 $RUSTUP_HOME $CARGO_HOME;
RUN USER=root cargo new --bin rpckafka
RUN cd ./rpckafka
WORKDIR /rpckafka

# copy over your manifests
# COPY ./Cargo.lock ./Cargo.lock
COPY ./Cargo.toml ./Cargo.toml

# this build step will cache your dependencies
# RUN cargo run
RUN rm src/*.rs

# copy your source tree
COPY ./src ./src
COPY ./.env ./.env


# RUN cargo build --release
# WORKDIR /rpckafka/target/release
EXPOSE 3032
COPY ./.env ./.env
ENTRYPOINT ["/usr/local/bin/aeronmd"]
